# Generated by Django 4.0.6 on 2022-07-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_alter_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
