# Generated by Django 4.0.6 on 2022-07-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0004_follow_remove_animal_liked_delete_like_follow_animal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='value',
        ),
    ]
