# Generated by Django 4.0.6 on 2022-08-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0005_remove_follow_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-publish',)},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ('-publish',)},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
